<?php

/**
 * BaseSitefooUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property date $birth_date
 * @property string $country
 * @property string $time_zone
 * 
 * @method string      getFirstName()  Returns the current record's "first_name" value
 * @method string      getLastName()   Returns the current record's "last_name" value
 * @method string      getEmail()      Returns the current record's "email" value
 * @method date        getBirthDate()  Returns the current record's "birth_date" value
 * @method string      getCountry()    Returns the current record's "country" value
 * @method string      getTimeZone()   Returns the current record's "time_zone" value
 * @method SitefooUser setFirstName()  Sets the current record's "first_name" value
 * @method SitefooUser setLastName()   Sets the current record's "last_name" value
 * @method SitefooUser setEmail()      Sets the current record's "email" value
 * @method SitefooUser setBirthDate()  Sets the current record's "birth_date" value
 * @method SitefooUser setCountry()    Sets the current record's "country" value
 * @method SitefooUser setTimeZone()   Sets the current record's "time_zone" value
 * 
 * @package    sitefoo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSitefooUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sitefoo_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('birth_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('time_zone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}