<?php

/**
 * SitefooUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitefooUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitefooUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SitefooUser');
    }
    
    // @claudiob - List available countries
    static public $countries = array(
      'IT' => 'Italy',
      'US' => 'United States of America',
      'FR' => 'France',
    );
    public function getCountries() {
      return self::$countries;
    }
}