<?php

/**
 * SitefooUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitefooUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitefooUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SitefooUser');
    }
}