# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sitefoo
    description:  A Sitefoo page
    keywords:     "sitefoo, web"
    language:     en
    robots:       all
    viewport:     "width=1000"
    author:       "Claudio Bacciglaupo"
    version:      0.1
    copyright:    Sitefoo

  stylesheets:    [main.css]

  javascripts:    [jquery.min.js, jquery.validate.js, main.js]

  has_layout:     true
  layout:         layout
